---
abstract: unknown
author:
  - 'Lefebvre Loic <lle@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: mbtget
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006_001
resources:
  repository: https://github.com/sourceperl/mbtget.git
version: v1.4.2
